### ISSUE TITLE
Build custom icons

### ISSUE THREAD

**Issue by bomastudio** [swisnl/jQuery-contextMenu#392]
A simpler way to use custom icons than install npm? Can I modify some *.css file? If yes, which one?

**Comment by nelson6e65** [comment]
You may _use_ custom icons. Check this example in documentation:.
https://swisnl.github.io/jQuery-contextMenu/docs/items#icon

**Comment by nelson6e65** [comment]
I found a better way to **use** custom [FontAwesome](http://fontawesome.io) icons by adding a new icon rule.

CSS for a 'view' icon:
```css
.context-menu-icon-view:before {
  content: "\f045"; /* Unicode for ".fa-share-square-o" icon*/
  font-family: "FontAwesome" !important;
}
```

Usage:
```js
items: {
  view: {name: "View", icon: "view"}, // This is own custom FontAwesome icon
  edit: {name: "Edit", icon: "edit"}
}
```
